version: "3"
name: xwsbot
services:

  elobot:
    image: docker.io/sogemoge/4-A7:latest
    container_name: inventory_droid
    environment:
      - COMPOSE_PROJECT_NAME
    restart: always
    ports:
      - 0.0.0.0:8080:801
    volumes:
      # - type: bind
      #   source: ./elo.db
      #   target: /opt/4-A7/elo.db
      - type: bind
        source: ./.env
        target: /opt/4-A7/.env

#    healthcheck:
#      test: ["CMD", "curl", "127.0.0.1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
