name: Manual maintenance override

on: workflow_dispatch

jobs:
  reboot:
    runs-on: ubuntu-latest
    steps:
      - name: Contingency protocol
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.REMOTE_MAINTENANCE_TARGET }}
            ${{ secrets.REMOTE_TARGET }}
            cd ${{ secrets.REMOTE_MAINTENANCE_TARGET }}
            git submodule update --recursive --remote
            systemctl restart xwsbot.maintenance.service