name: Manual override

on: workflow_dispatch

jobs:
  reboot:
    runs-on: ubuntu-latest
    steps:
      - name: Contingency protocol
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            git checkout master && git stash && git fetch --all && git reset --hard origin/master
            git submodule update --recursive --remote
            systemctl restart xwsbot.service